export const MOCK_STATS = [
  {
    title: "Total Workspaces",
    value: "12",
    description: "+2 this week",
    trend: "up",
    icon: "Folder",
  },
  {
    title: "Saved Resources",
    value: "148",
    description: "+15 this week",
    trend: "up",
    icon: "FileText",
  },
  {
    title: "AI Chat Sessions",
    value: "34",
    description: "+8 this week",
    trend: "up",
    icon: "Sparkles",
  },
  {
    title: "Quizzes Generated",
    value: "27",
    description: "Across 5 workspaces",
    trend: "neutral",
    icon: "BrainCircuit",
  },
];

export const MOCK_WORKSPACES = [
  {
    id: "w-1",
    title: "Machine Learning Concepts",
    description: "Notes and research papers on neural networks, transformers, and deep learning architectures.",
    resourceCount: 24,
    lastUpdated: "2 hours ago",
    badges: ["AI", "Research"],
    color: "bg-blue-500",
  },
  {
    id: "w-2",
    title: "System Design Prep",
    description: "Architecture diagrams, scalability concepts, and distributed systems notes for interviews.",
    resourceCount: 15,
    lastUpdated: "1 day ago",
    badges: ["Engineering", "Study"],
    color: "bg-[#4A00FF]",
  },
  {
    id: "w-3",
    title: "Q3 Marketing Strategy",
    description: "Campaign ideas, competitor analysis, and budget planning for the upcoming quarter.",
    resourceCount: 8,
    lastUpdated: "3 days ago",
    badges: ["Marketing", "Planning"],
    color: "bg-emerald-500",
  },
];

export const MOCK_ACTIVITIES = [
  {
    id: "a-1",
    type: "upload",
    title: "Uploaded PDF",
    description: "Attention Is All You Need.pdf added to Machine Learning Concepts",
    timestamp: "10 mins ago",
    icon: "FileUp",
    color: "text-blue-400",
    bg: "bg-blue-400/10",
  },
  {
    id: "a-2",
    type: "quiz",
    title: "Generated Quiz",
    description: "15 questions generated from System Design prep notes",
    timestamp: "2 hours ago",
    icon: "HelpCircle",
    color: "text-[#4A00FF]",
    bg: "bg-[#4A00FF]/10",
  },
  {
    id: "a-3",
    type: "workspace",
    title: "Created Workspace",
    description: "New workspace 'Q3 Marketing Strategy' initialized",
    timestamp: "1 day ago",
    icon: "FolderPlus",
    color: "text-emerald-400",
    bg: "bg-emerald-400/10",
  },
  {
    id: "a-4",
    type: "summary",
    title: "Generated Summary",
    description: "Summarized 45 pages of React Documentation",
    timestamp: "2 days ago",
    icon: "FileText",
    color: "text-amber-400",
    bg: "bg-amber-400/10",
  },
];
